language: java
jdk:
- oraclejdk8
services:
- docker
ssh_known_hosts:
- openshift.opencontainer.io:8443
env:
  global:
  - DOCKER_IMAGE_NAME=vikaspogu/demo
  - secure: rJ1wlLK+1CJVzpN+mz9yC46W48PW6Zp8JtfgTiuK3Hjpx12A8++0BCWUWiqiCzD6jl4ZQVpsbT0s3gMfl+2i0kWJivcP3o/JMsFkKjjH8IIjeb/IZSsaaLrBM3J8HB4sHZeW4VB/K4CmXzy0ni4+kVgJqAVZjVycDyV334W7EVoO1Ut6qVbhcNKf4nHcgt1WBnIKFrRv3qQlHY4O4B+7DYhMaROIJYNn4/iqP5hv90KYd49Fp4DfiizlbT+sfvTevMrznMW9yo6WDZTaYY86Mw1WqkpdlMOrBDqpR6GLGgD8KfOyhI77csjWZA/bfP39g9bAu2ibSSCCUV+gLaU+cpVeOcteW0jXMOrwtPTzWo5qPW6dc2D/f2kM8M35fxd14Ju1I7fHb+EVSbYurJv2e6AX4ENfEWJyfFW0dNmh1zCuKYAEzG3+nkiKFWx6z7GFJuJIDiLKmOLD8hg0VYgWvTPGD3TSwrRlA1O5NAZp6om8wH+xyS/U2s7GEo4LquatNHIkhRGbBlX1ITUg8DRwNcjNAtQU5ScKdkLd0LRYTq4HcbEw336eA3Q5bClofOQGeBEFYkgE8RnLboeKpnnCSsp9YFslWgQvklV10hnrO1VQZ9/ciA6Ua0j5XFfdnil9qfzpxTjmxvCHvgBAqC8488fJAGkdpN35RS9rN8IhWjQ=
  - secure: aPKp60oSAAB83KwPaWYahHvrHTv0X+VymL1BfT0TZQ/xK2G3yW+qQjQeO2Ib0Y/pNiMQwdqUo8XsZ8plT6QzfETKbUyeZJSJffHuERk5UETndCD/zBTjRK/3X967TptkdnChEc/CK2C1AoyVXfV+/9ydppZU4ESwwucFecQlY6leFT7+2WXr6E9AgctYhSRnh1NyDwlBzGXsxJvBBZl6wmAFBGcNYeVXom9wWyfDx2M+lcGVg3O4eWBQXIrW8qsX5uieqboEFSR+vu/khjc5JmhK3bdtaFqnJVTr2mkrkUSaRdVVC1oOo2Uiunb3i6EUr38kxqU8SkcLijkc4TVfmj3vEhH3HCszOivSsw2vHaaJfRp9+L4HPLF4j6gL2ypGvAv8Er47yvj1JNVo5B1MxV0ymHD+kO9zEty5ayMiSadJJVuYSNMxtLY2VB43aqVkFnJYfpB4YrG//vNC1apZJxEb7cCGKFjqGlNRz+gLuTHdYyhn44Xp/erdpTc1pa669cm20syqHCg4RD6w2Vf5FaYQpK6T7mFp0eRrFgcUSPoCbfkynTgzEX8fHklJr8kIdEtBBuMAonzfMTeN3GLKZzKlPaYiKNEM0LBVcmHClL4c6XIVj93LPwrZPTPIB6OTh7JTbq8zWsiLBWG+tYVy6mvjpBpzNw7p8jC4qCQkYDw=
  - secure: c6ShaC+RywY+psmwmrpn3yZkygXpE9d514fDgzQfxCShFKx9zYtN6RHJpNW/4BwCXkcr8ndI4djCOSmnz1SsY76Sckn6nbL2m273NiOK/Xkrat7VY69yaH3wTbkp7chBndXFzMpALqnx5vKY/YE3DcGVxgJ8/bEZhcemZevQOtz2oE21FeZAgntnZ13ys+rt+3UO3upEedcd+UNxPEG3oX8ChTs0eR7Dx+CdIoGmYnUO1IgFqrvOzO1oZxVfMXpZ8bPelxRLXEciLtOl77BMVdCFtfBXswyIKhvCj3XJsNWX7neUYVP5EeHVtfk6dGeJVqKDBZEkdilA6sO6U6FO+zrGoelfCZzUsHn80L4sJ/VumxinIj/f+RqSPYgzfsxAy3WbwUj7UFvgdPQQUVkbE+D6woXX1ASp2MML3jpqmWrJgdxrFNcmIhz6dn9H7Fq86C/vczBBLIhWpmH26nnKaOmMI0IRFFx7doYXBr2tv/khESTFfeHIZZvgMIsEIeN4O+UohG02pnSjoWAF32WwcA3dlb+uSQiK9KirPpK9GlKJrkT0RbyZmY7oQvlCzb+plEETF5PrJwGt74//RVovrSQ/0Ad47YKRjg09jMc4urVKRvlf0rUuETt5/I5b3MzK4js81OtOkN1Kuvh0VKI9saRugeDQTqLN4hJW/2YpLac=
before_install:
- curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
- chmod 700 get_helm.sh
- sudo ./get_helm.sh
- wget https://github.com/openshift/origin/releases/download/v1.5.1/openshift-origin-client-tools-v1.5.1-7b451fc-linux-64bit.tar.gz
- tar xvzf openshift-origin-client-tools-v1.5.1-7b451fc-linux-64bit.tar.gz && sudo mv openshift-origin-client-tools-v1.5.1-7b451fc-linux-64bit /usr/local/bin/oc && export PATH=/usr/local/bin/oc:$PATH
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jobs:
  include:
  - stage: build
    script:
    - helm lint ./sample-helm
    if: branch = master AND type IN (push)
    after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build -t ${DOCKER_IMAGE_NAME}:$TRAVIS_BUILD_NUMBER .
    - docker push ${DOCKER_IMAGE_NAME}
    - oc login https://openshift.opencontainer.io:8443 -u admin -p $OSE_PASS --insecure-skip-tls-verify
    - helm upgrade --install sample-helm ./sample-helm --set=image.tag $TRAVIS_BUILD_NUMBER --namespace=demo-sample --tiller-namespace=tiller
